
    - name: Install tmux terminal multiplexer
      apt: pkg=tmux
      become: yes

    - name: Create ubnutu user
      user: name=ubuntu
      become: yes

    - name: Create emp directory
      file: path=/emp state=directory owner=ubuntu group=ubuntu
      become: yes

    - name: Copy docker-compose configuration
      copy: src=docker-compose.yml dest=/emp owner=ubuntu group=ubuntu
      become: yes

    - name: Copy upstart script for docker services
      copy: src=docker-services.conf dest=/etc/init/ mode=0644
      become: yes


    - name: Add ubuntu user to docker group
      user: name=ubuntu groups=docker append=yes
      become: yes

    - name: Restart docker-services
      service: name=docker-services state=restarted
      become: yes
